### ISSUE TITLE
How you generate documentation ?

### ISSUE THREAD

**Issue by elhoucine** [krkn/kouto-swiss#41]
Thanks for this great framework. 

I wanna ask what tools do you use to generate documentation ?

I want to use it for my project.

Thanks.

**Comment by leny** [comment]
Hi,

It's an *homemade*, *quick'n'dirty* system, using markdown & jade, and grunt to build.

You will find all you need in the `Gruntfile.js` file at the root of the project, and in `_doc` folder.

**Comment by elhoucine** [comment]
Thanks :+1:
