### ISSUE TITLE
How to use kouto-suiss with Grunt

### ISSUE THREAD

**Issue by elhoucine** [krkn/kouto-swiss#42]
##### " For grunt, you can use grunt-contrib-stylus, and include kouto swiss in your use option for the task. "

I didn't know how.

Here is my Gruntfile:

     module.exports = function(grunt){
        grunt.initConfig({

            watch:{
                scripts:{
                    files: ['layer-css/*/*.styl'],
                    tasks: ['stylus'],
                    options: {
                        spawn: true
                    }
                }
            },

            stylus: {
                compile: {
                    files: {
                      'css/style.css': ['layer-css/**/*.styl']
                    },
                    options: {
                        compress: false, // For developement only :)
                        linenos: true, // Adding comments indicating the corresponding stylus line.
                        use: [ function(){
                            return require('kouto-swiss') }
                        ] /* Im not sure how this works */
                    },
                }

            }
        });

        grunt.loadNpmTasks('grunt-contrib-watch');
        grunt.loadNpmTasks('grunt-contrib-stylus');

        grunt.registerTask('default', ['watch']);
      };

**Comment by leny** [comment]
Hi, 

This version is correct :
```
stylus: {
            compile: {
                files: {
                  'css/style.css': ['layer-css/**/*.styl']
                },
                options: {
                    compress: false, // For developement only :)
                    linenos: true, // Adding comments indicating the corresponding stylus line.
                    use: [ require('kouto-swiss') ]
                },
            }
        }
```

Regards,

**Comment by elhoucine** [comment]
Thanks leny,

but I'm little confusing.

    height: percent(20, 250);

Doesn't change after compilation. style.css

     height: percent(20, 250);

Do I have to @import "kouto-suiss" in my .styl files or somehting ?

**Comment by leny** [comment]
Yes, as for any Stylus libraries, after you're include it, you need to load it inside your stylesheets with `@import "kouto-swiss"`.

**Comment by elhoucine** [comment]
Yo Pierre-Antoine I get it thank you very much :)
