### ISSUE TITLE
Unprefixed CSS for Position Sticky

### ISSUE THREAD

**Issue by srsgores** [krkn/kouto-swiss#43]
I would expect the following, when using ``position sticky``, given [the current state of support in browsers](http://caniuse.com/#search=sticky):

```
  position: -webkit-sticky;
  position: -moz-sticky;
  position: -ms-sticky;
  position: -o-sticky;
```

But I just get:

```
position: sticky;
```

**Comment by leny** [comment]
Hi, thanks for the report,

I'm kind of busy right now (got a bad space-flu, completely *out*), so if you're feeling for a PR, go for it. If not, I will try to make it in the week.

**Comment by leny** [comment]
Has been implemented & published in version `0.11.7`.

Thanks again.

**Comment by srsgores** [comment]
Looks like you're still missing the corresponding docs on the ``sticky`` mixin.

**Comment by leny** [comment]
Argh. Will add it soon. Thanks for the report.

**Comment by leny** [comment]
Fixed and published. :)
