### ISSUE TITLE
Please get rid of the rotate stuff?

### ISSUE THREAD

**Issue by sdegutis** [krkn/kouto-swiss#45]
I just looked at http://kouto-swiss.io for like 10 seconds, and it made me really dizzy and sick to my stomach. I closed it and I still feel this way a few minutes later. Please drop this rotate thing. Please??

**Comment by leny** [comment]
Hi,

I'm not sure about what you are talking about : you mean the red background headers, rotate backwards ?
I'm sorry that you feel this way, but I don't think its an issue by itself.

I don't plan to change the website nor the documentation soon, and you are the first ever complaining about a thing that is, by definition, a design choice, which, I concede, can't please to anyone.

By the way, on the [documentation page](http://kouto-swiss.io/docs.html), which is the only one you'll need to use the project, there is just two discrete "rotate stuffs", which I hope will make you less dizzy and allows you to browse the documentation to make your opinion on the library, which can help you make many things with stylus - rotating or not :wink: 

> Besides that, Kouto Swiss stills open-source, and if you feel in mood to propose a new design for the website and/or documentation, feel free to submit a Pull Request.

Regards,

**Comment by sdegutis** [comment]
@leny there's a difference between a difference in taste and actually becoming sea-sick due to a design. I tried to make a PR instead of an issue, but it seems your website's CSS is *entirely written in a single line* which makes that really difficult.

**Comment by leny** [comment]
You are looking the compiled stylesheet.

If you want to try and modify the website, you can checkout the kouto swiss repository, and the files are in the `_docs` folder.  
The stylesheet is `_docs/_styles/` folder.

Using [grunt](http://gruntjs.com), you can build the website with the `grunt default` task, or previewing it locally with the `grunt preview` task.

* * *
I'm still that you are the only one - at this point - pointing me this problem. Maybe it's not the rotate boxes but the intensity of the red color ?  
I'm myself colorblind and some rare colors makes me feel dizzy when used on big zones or luminous screens...

**Comment by sdegutis** [comment]
@leny I suspected the one-line CSS file was compiled output, thanks for pointing me to the source. And yes, it is definitely 100% the rotation that made me sick and dizzy (still am fwiw). And chances are, I'm not the only one who it made dizzy, and the others just simply left your site and never took a serious look at Kouto because of it. It's a small gesture you can do to the community to show that you care about avoiding making a few of us nauseous with this design decision. Plus it may increase the lib's usership. I'll send PR in a minute so you can decide.

**Comment by sdegutis** [comment]
Sent PR.

**Comment by leny** [comment]
I will make some styles adaptations and push it on the evening - I've got some failing unit tests on a mixin I want to fix to publish a release of the lib in the same move.
Thanks for your contribution.

**Comment by sdegutis** [comment]
:cake:

**Comment by morenoh149** [comment]
I think the design is fine. Though I'm not a designer. And believe @sdegutis could have worded his grievances more professionally.

**Comment by sdegutis** [comment]
@morenoh149 very true, although to be fair, an unavoidable sense of urgency comes with feeling like you have to vomit

**Comment by leny** [comment]
If some little adaptations on the design can help some visitors to feel more comfortable with their stomach, I will make them.  
I won't be responsible for keyboards drowned in gastric fluids :wink:

**Comment by leny** [comment]
The modifications are online.

I had to fix the position mixin - which is published as version `0.11.8`.

**Comment by sdegutis** [comment]
Thanks!
