### ISSUE TITLE
Question: remove grunt peerDependency?

### ISSUE THREAD

**Issue by freeformsystems** [krkn/kouto-swiss#47]
It seems illogical that grunt should be declared as a `peerDependency`, our project uses `gulp` and has no need for grunt.

Could you explain why this is necessary please?

**Comment by leny** [comment]
Hi, thanks for the report.

It was a relic from the project scaffolding, thanks for noticing it.

Its fixed and published on npm as `0.11.9`.

**Comment by freeformsystems** [comment]
Thanks for the quick response and registry publish - appreciated! :)

**Comment by leny** [comment]
You were lucky I was still awake - its 4 A.M. here in Belgium. :wink:
