### ISSUE TITLE
Thoughts on converting to colon based syntax?

### ISSUE THREAD

**Issue by corysimmons** [krkn/kouto-swiss#48]
It seems like Stylus `rc-1.0` will make colon-based syntax mandatory.

https://github.com/LearnBoost/stylus/wiki/1.0.0#syntax

**Comment by leny** [comment]
Hi, thanks for the info.

I'm very busy this week, but I'll try to take a look ASAP.

**Comment by leny** [comment]
Fixed & published as version `0.11.12`. Sorry for the *very long* delay.
