### ISSUE TITLE
Duplicate font-family declaration (normalize)

### ISSUE THREAD

**Issue by freeformsystems** [krkn/kouto-swiss#49]
Seems like an error to me:

https://github.com/krkn/kouto-swiss/blob/fd0b3cfcae82355437b5e6efe12d4b2a02a3edb5/lib/kouto-swiss/reset/normalize.styl#L100

Results in:

```
font-family: monospace, monospace;
```

**Comment by leny** [comment]
Hi, thanks for the report.

It's a strict import from normalize.css, as you can see [here](https://github.com/necolas/normalize.css/blob/master/normalize.css#L233).

Still, I don't know if its a bug from their side or if there's a reason to do that.

I will make some search about this.

**Comment by leny** [comment]
**Note:** there's a reason for the double `monospace` in the css, it's explained [here](https://github.com/necolas/normalize.css/pull/348).

Thanks for noticing it, I've learn something :wink:
