### ISSUE TITLE
Missing mixin which nib has.

### ISSUE THREAD

**Issue by BYODKM** [krkn/kouto-swiss#50]
`box-shadow()`

https://github.com/tj/nib/blob/master/lib/nib/vendor.styl#L60

I've tested kouto-swiss and noticed that box-shadow mixin is missing.
It's not big deal. But it would be perfect if kouto-swiss has it.

**Comment by leny** [comment]
Hi,

Thanks for the report.

As you can see [here](http://caniuse.com/#search=box-shadow), the support for box-shadow is nearly universal, and thus can be ignored.

Besides that, I can add it when I have some time. Feel free to propose a Pull Request for that.

**Comment by leny** [comment]
Published on npm as version `0.11.10`
